name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      
    - name: Check out the repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0


    - name: Git Semantic Version
      uses: PaulHatch/semantic-version@v4.0.3
      with:
        # The prefix to use to identify tags
        tag_prefix: "v"
        # A string which, if present in a git commit, indicates that a change represents a
        # major (breaking) change, supports regular expressions wrapped with '/'
        major_pattern: "(MAJOR)"
        # Same as above except indicating a minor change, supports regular expressions wrapped with '/'
        minor_pattern: "(MINOR)"
        # A string to determine the format of the version output
        format: "${major}.${minor}.${patch}-prerelease${increment}"
      id: semversion


    - name: Docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo "Iniciando logging en Docker Hub..."
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin
        echo "Login satisfactorio!"


    - name: Build Docker Image
      env:
        VERSION: ${{ steps.semversion.outputs.version }}
      run: |
        docker build -t correocamg/docker-graphql:$VERSION .
        docker build -t correocamg/docker-graphql:latest .


    - name: Push Docker Image
      env:
        VERSION: ${{ steps.semversion.outputs.version }}
      run: |
        docker push correocamg/docker-graphql:$VERSION
        docker push correocamg/docker-graphql:latest
